apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: gcr.io/cs166-327318/florescss14/sentiment-analysis-frontend@sha256:ba91a730b46fc8a79b96e7ffcfc886b88b0f50bb5931f16bc1311e50c3587d6a 
      name: sa-frontend
      ports:
        - containerPort: 80