apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      containers:
        - image: gcr.io/cs166-327318/florescss14/sentiment-analysis-frontend@sha256:ba91a730b46fc8a79b96e7ffcfc886b88b0f50bb5931f16bc1311e50c3587d6a
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80
