apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  selector:
     matchLabels:
       app: sa-logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
        - image: gcr.io/cs166-327318/florescss14/sentiment-analysis-logic@sha256:9fccda4c24e5560b66502b9a0dadeff822861aa138cb79775f26d99d27fb927a
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
